### ISSUE TITLE
Create AbstractStringToken..

### ISSUE THREAD

**Issue by lemonboston** [dmfs/http-client-essentials-suite#29]
..so there would be no need to implement delegation in all Tokens that rely on a String.
(The need came up in a concrete client api library.)

**Comment by lemonboston** [comment]
Just a note: would it make sense to create a lazy version, which only evaluations a let's say `abstract String createValue()` method when any of the `CharSequence` methods are called and then caches the value?

**Comment by dmfs** [comment]
Yes a lazy + caching version would be good. Instead of having an abstract `createValue` method we could just pass a `StringTokenFactory` to the constructor, though ("Factory" is probably not the right term here). That might make it easier to recycle stuff, because you can decorate the factory but you can't decorate the `createValue` method once implemented (because the implementing class is supposed to be `final`).

**Comment by lemonboston** [comment]
Yes, sounds better with the factory. One more note: to be able to re-use for all `CharSequence`, not just `Token`, we could make this general, like AbstractStringCharSequence / AbstractLazyStringCharSequence.

**Comment by dmfs** [comment]
I think this has become obsolete with `AbstractBaseToken`.

**Comment by lemonboston** [comment]
Yes, most probably, I close it.
